export const field = {
  name: {
    name: 'name',
    type: 'text',
    placeholder: 'Name*',
    title: 'The name must consist of at least 3 characters!',
    required: true,
  },
  email: {
    name: 'email',
    type: 'text',
    placeholder: 'Email*',
    required: true,
  },
  password: {
    name: 'password',
    type: 'password',
    placeholder: 'Password (from 8 characters)*',
    required: true,
    title: 'The password must be at least 8 characters long',
  },
  height: {
    name: 'height',
    type: 'text',
    placeholder: 'Height (100-250)*',
    required: true,
    title: 'Enter a valid integer between 100 and 250.',
  },
  age: {
    name: 'age',
    type: 'text',
    placeholder: 'Age (18-100)*',
    required: true,
    title: 'Enter a valid number between 18 and 100.',
  },
  weight: {
    name: 'weight',
    type: 'text',
    placeholder: 'Current weight (20-250)*',
    required: true,
    title: 'Enter a valid integer between 20 and 250.',
  },
  desiredWeight: {
    name: 'desiredWeight',
    type: 'text',
    placeholder: 'Desired weight (20-500)*',
    required: true,
    title: 'Enter a valid integer between 20 and 500.',
  },
  bloodType: {
    name: 'bloodtype',
    type: 'text',
    placeholder: 'Blood type*',
    disabled: true,
  },
  filter: {
    type: 'text',
    name: 'filter',
    placeholder: 'Filter by name',
  },
};
